### ISSUE TITLE
Забыть определенный ключ

### ISSUE THREAD

**Issue by decadence** [arrilot/bitrix-cacher#1]
Есть ли возможность в Bitrix забыть определенный ключ из кеша или только полная отчистка через flush?

**Comment by arrilot** [comment]
Ключ - нет. Но можно вместе с ключом указать $initDir и очищать эту директорию через https://github.com/arrilot/bitrix-cacher/blob/master/src/Cache.php#L72

Теоретически можно класть каждый ключ в свою директорию и тогда очистка директории очистит лишь один ключ

**Comment by decadence** [comment]
Да, есть такой вариант, но как-то накладно для каждого ключа свою директорию. Ну ладно, спасибо.
